// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommercialIntro: typeof import('./src/components/CommercialIntro.vue')['default']
    CommercialPhotoCarousel: typeof import('./src/components/CommercialPhotoCarousel.vue')['default']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    FooterLinks: typeof import('./src/components/FooterLinks.vue')['default']
    FooterMap: typeof import('./src/components/FooterMap.vue')['default']
    FooterTopSection: typeof import('./src/components/FooterTopSection.vue')['default']
    FormStep: typeof import('./src/components/FormStep.vue')['default']
    FormWizard: typeof import('./src/components/FormWizard.vue')['default']
    HomeBottomQuoteButton: typeof import('./src/components/HomeBottomQuoteButton.vue')['default']
    HomeCheckSocial: typeof import('./src/components/HomeCheckSocial.vue')['default']
    HomeGoogleReviews: typeof import('./src/components/HomeGoogleReviews.vue')['default']
    HomeLogo: typeof import('./src/components/HomeLogo.vue')['default']
    HomeNav: typeof import('./src/components/HomeNav.vue')['default']
    HomeServices: typeof import('./src/components/HomeServices.vue')['default']
    HomeServicesItem: typeof import('./src/components/HomeServicesItem.vue')['default']
    HomeTopButtons: typeof import('./src/components/HomeTopButtons.vue')['default']
    HomeVideo: typeof import('./src/components/HomeVideo.vue')['default']
    HomeWhatSeparates: typeof import('./src/components/HomeWhatSeparates.vue')['default']
    HomeWhatSeparatesItem: typeof import('./src/components/HomeWhatSeparatesItem.vue')['default']
    QuoteForm: typeof import('./src/components/QuoteForm.vue')['default']
    ResidentialIntro: typeof import('./src/components/ResidentialIntro.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheGetQuoteButton: typeof import('./src/components/TheGetQuoteButton.vue')['default']
    TheTopSection: typeof import('./src/components/TheTopSection.vue')['default']
    TopWarningBox: typeof import('./src/components/TopWarningBox.vue')['default']
  }
}
